name: idletd
version: 1.1
main: io.github.stealingdapenta.idletd.Idletd
author: StealingDaPenta
description: The best idle Minecraft Tower Defense game!
api-version: 1.20
depend: [WorldGuard, FastAsyncWorldEdit]


commands:
  p:
  plot:
    description:
    usage:
        /plot
        /plot new

  td:
  idletd:
  tower:
  towerdefense:
    description: Launches your Idle Tower Defense game!
    usage: /<command>
