name: idletd
version: 1.1
main: io.github.stealingdapenta.idletd.Idletd
author: StealingDaPenta
description: The best idle Minecraft Tower Defense game!
api-version: 1.20
depend: [WorldGuard, FastAsyncWorldEdit]


commands:
  zombie:
    description: Spawn a zombie.
    usage: /<command>

  tracker:
    description: Give yourself the tracker item.
    usage: /<command>

  plot:
    description:
    usage:
        /plot
        /plot new
