name: idletd
version: 1.1
main: io.github.stealingdapenta.idletd.Idletd
author: StealingDaPenta
description: The best idle Minecraft Tower Defense game!
api-version: 1.20
depend: [WorldGuard, FastAsyncWorldEdit, Citizens]


commands:
  plot:
    description:
    usage:
        /plot
        /plot new
    aliases: [p]

  towerdefense:
    description: Launches your Idle Tower Defense game!
    usage: /<command>
    aliases: [td, idletd, tower]

  agent:
    description: Temporary debug command to summon main agent.
    usage: /<command>
