-- Create the PLOT table with unique constraint on PLAYERUUID
create TABLE IF NOT EXISTS PLOT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STARTX INT NOT NULL,
    STARTZ INT NOT NULL,
    PLAYERUUID VARCHAR(36) NOT NULL UNIQUE);


-- Insert Default value if needed
insert into PLOT(STARTX, STARTZ, PLAYERUUID) values (0, 0, 'SERVER');
COMMIT;



-- Create the IDLE_PLAYER table
create TABLE IF NOT EXISTS IDLE_PLAYER (
    PLAYERUUID VARCHAR(36) PRIMARY KEY NOT NULL,
    BALANCE DOUBLE NOT NULL,
    FK_PLOT INT,
    FOREIGN KEY (FK_PLOT) REFERENCES PLOT(ID)
);


-- Create the TowerDefense game table
create TABLE IF NOT EXISTS TOWER_DEFENSE (
    PLAYERUUID VARCHAR(36) PRIMARY KEY NOT NULL,
    FK_PLOT INT NOT NULL,
    STAGE_LEVEL INT NOT NULL,
    FOREIGN KEY (PLAYERUUID) REFERENCES IDLE_PLAYER(PLAYERUUID) ON delete CASCADE,
    FOREIGN KEY (FK_PLOT) REFERENCES PLOT(ID) ON delete CASCADE
);




